[package]
name = "lemon"
version = "2.1.2"
authors = ["mendess <pedro.mendes.26@gmail.com>"]
edition = "2018"
default-run = "lemon"

[dependencies]
once_cell = "1"
arc-swap = "1"
structopt = "0.3"
regex = "1"
itertools = "0.10"
enum-iterator = "0.6"
tokio-stream = { version = "0.1", features = ["io-util"] }
futures = "0.3"
derive_builder = "0.10"
chrono = "0.4"
array-init = "2"
unzip-n = "0.1"
glob = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }
signal-hook = "0.3"

[dependencies.tokio]
version = "1"
features = [ "sync", "rt", "rt-multi-thread", "net", "signal", "process", "time", "macros", "io-util", "io-std" ]

