[package]
name = "lemon"
version = "1.0.0"
authors = ["mendess <pedro.mendes.26@gmail.com>"]
edition = "2018"

[dependencies]
once_cell = "1"
arc-swap = "1"
signal-hook = "0.3"
structopt = "0.3"
regex = "1"
itertools = "0.10"
enum-iterator = "0.6"
